# ![](http://www.numpy.org/_static/numpy_logo.png) Introduction to NumPy
##### NumPy supports arrays which are very useful to numerical computations
* Arrays are N dimensional: 1d (vector), 2d (plane),...,N dim
* Many packages use numpy arrays to store data


* Arrays can be used to make calculations in one command, without loops or list comprehension.
  * This is known as *vectorisation*


* Using vectorisation will make your code faster, and easier to read.
  * Arrays are (generally) faster than lists.
  
See more in this guide: https://www.labri.fr/perso/nrougier/from-python-to-numpy/

And if you're transitioning from Matlab, you may find this helpful: https://numpy.org/doc/stable/user/numpy-for-matlab-users.html

### What is vectorisation?

Say you want to calculate an array of values `array2`, based on your original data in `array1`. 

Vectorised example:
```python
array2 = array1 * k + c
```

Non-vectorised example, requires a loop:
```python
for i in range(len(array1)):
    array2[i] = array1[i] * k + c   
```

Without vectorisation, multi-dimensional arrays would need multiple nested loops.

### Do we still need lists?

* Lists can have different objects as elements. Arrays are homogenous.
```python
example_list = [number, string, cat, dog]
example_array = [cat1, cat2, cat3]
```
* Lists can be nested. 
```python
nested_list = [[1, 2], ['a', 'b', 'qwerty'], [1]]
```
Arrays can be nested but it negates some of the advantages of n-dimensional arrays.
 

## Let's get started ...

In [1]:
import numpy as np

### Looking for help?

* Documentation: https://numpy.org/doc/stable/
* Use help function (remember tab will show options available)
```python
    help(np.mean)
```
* Interactive help: NumPy has an a built-in search engine

In [2]:
np.lookfor('weighted average')

Search results for 'weighted average'
-------------------------------------
numpy.average
    Compute the weighted average along the specified axis.
numpy.ma.average
    Return the weighted average of array over the given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.ma.MaskedArray.mean
    Returns the average of the array elements along given axis.
numpy.cov
    Estimate a covariance matrix, given data and weights.


### Creating an array from a list

In [3]:
a1d = np.array([3, 4, 5, 6])
a1d

array([3, 4, 5, 6])

In [4]:
a2d = np.array([[10., 20,  30], [9, 8, 5]])
a2d

array([[10., 20., 30.],
       [ 9.,  8.,  5.]])

In [5]:
print( type( a1d[0] ) )
print( type( a2d[0,0] ) )

<class 'numpy.int32'>
<class 'numpy.float64'>


In [6]:
type(a1d)

numpy.ndarray

The **core class** of NumPy is the `ndarray` (homogeneous n-dimensional array).

To find methods or attributes:

```
a1d.   ->tab
```
More on this below...

---

### Array attributes

In [8]:
# a reminder of what we're working with:
a2d = np.array([[10., 20,  30], [9, 8, 5]])
type(a2d)

numpy.ndarray

#### ndarray.ndim
the number of dimensions (axes) of the array. In NumPy, the number of dimensions is referred to as rank.

In [9]:
a2d.ndim

2

#### ndarray.shape
the dimensions of the array

In [10]:
a2d.shape

(2, 3)

This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m).  
The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

In [11]:
# Let's use those values

NLines,NCols = a2d.shape
print(f'NLines: {NLines} NCols: {NCols}')

NLines: 2 NCols: 3


#### ndarray.size
the total number of elements in the array

In [12]:
a2d.size

6

Note that for an ND array `size` is not equal to `len()`. The latter returns the length of just the *first* dimension.

In [13]:
len(a2d)

2

#### ndarray.dtype

type of data within the array

In [14]:
a2d.dtype

dtype('float64')

---

### Aside: Common mistakes when creating arrays

Say we forget to use the square brackets:

In [15]:
try:
    a = np.array(1,2,3,4)   # WRONG, only 2 non-keyword arguments accepted
except TypeError as err:
    print(f'TypeError: {err}')

# help(np.array)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given


In [16]:
a = np.array([1,2,3,4]) # RIGHT
print(a)

[1 2 3 4]


Arrays can be created using `np.ndarray`, but this works differently to `np.array`. Here you specify the dimensions within the first set of square backets.

In [17]:
np.ndarray([1,2,3,4]) #  This is not the recommended way to create arrays

array([[[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
          9.45716656e-308],
         [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
          6.23057349e-307],
         [8.01100605e-307, 1.60220393e-306, 9.34593493e-307,
          6.23059726e-307]],

        [[1.60221208e-306, 8.90071985e-308, 1.24610383e-306,
          1.69118108e-306],
         [8.06632139e-308, 1.20160711e-306, 1.69119330e-306,
          1.29062229e-306],
         [6.89804133e-307, 1.11261162e-306, 8.34443015e-308,
          3.91792476e-317]]]])

Result: an "empty" 4-D array.

This is not the recommended method for creating arrays. `ndarray` is a class, with `array` the recommended function. 

Below is a number of other possible methods for allocating arrays. 

---

## Functions for creating arrays

#### ``np.arange([start,] stop[, step,], dtype=None)``

evenly spaced, *defined by step*

In [18]:
# you don't have to use integers
np.arange(1, 9, 2.)

array([1., 3., 5., 7.])

In [19]:
# but for integers, np.arange is similar to what we saw earlier when using range 
np.array( range(1,9,2) )

array([1, 3, 5, 7])

#### ``np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)``

evenly spaced, *defined by length*

In [20]:
np.linspace(0, 1, 10)   # start, end, num-points

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Note that for ``np.linspace`` the upper value is included within the array. 
This is different to the result for ``range`` or ``np.arange``.  

---

## Exercise 1

In [23]:
# a) Create array with units of seconds through the day, from 00:00 to 24:00, inclusive 
# b) Create new arrays that still have units of seconds but have 1 minute or 1 hour intervals.
# (enter your code below)


---

### More functions for creating arrays


#### Empty array

In [24]:
np.empty((2,2))

array([[1., 3.],
       [5., 7.]])

As seen in the example with `ndarray` above, the array is not truly empty. Result is an array of *uninitialised* (arbitrary) values. 

This method should only be used if all values will be allocated at a later stage i.e. use with caution. 

####  Array filled with zeros

In [32]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

By default, the dtype of the created array is float64 but other dtypes can be used:

In [33]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

#### Filled with ones

In [35]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Filled with random numbers

In [43]:
np.random.rand(4)       # sampled from uniform distribution between 0-1

array([0.32912018, 0.60478055, 0.15645472, 0.40702871])

In [44]:
np.random.normal(0, 10, size=4)      # Gaussian (mean, std dev, size/num samples)

array([-5.03949099,  9.49084194, 10.51909197,  8.05485738])

In [45]:
np.random.gamma(1, 1, (2,2))      # Gamma (shape of distribution, scale, size/num samples)

array([[1.2727409 , 0.18552237],
       [1.29403343, 0.01723177]])

As you can see, you can get multiple outputs in whatever distribution you'd like. 

The keyword for 'size' is optional. Note that in the third example, size is given as a tuple.

### Grid generation

A common task is to generate a pair of 2D (or ND) arrays that represent data coordinates - useful for interpolation or mapping contours.

When orthogonal 1D coordinate arrays already exist, NumPy's `meshgrid` function is very useful:

In [47]:
x = np.linspace(-5, 5, 3)
y = np.linspace(10, 40, 4)
print(x)
print(y)

[-5.  0.  5.]
[10. 20. 30. 40.]


In [48]:
x2d, y2d = np.meshgrid(x, y)
print(x2d)
print(y2d)

[[-5.  0.  5.]
 [-5.  0.  5.]
 [-5.  0.  5.]
 [-5.  0.  5.]]
[[10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]
 [40. 40. 40.]]


### Transpose arrays 
This can be very useful when dealing with grids (or 2D arrays), and there are several ways to do this:

In [51]:
print(y2d,'\n')
print(np.transpose(y2d),'\n') # using a numpy function
print(y2d.transpose(),'\n')   # using a method of y2d
print(y2d.T)                  # using a property of y2d (i.e. a specific version of general methods above)

[[10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]
 [40. 40. 40.]] 

[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]] 

[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]] 

[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]


---

---

# Exploring arrays: Array indexing

* Indices begin at 0, like other Python sequences and C/C++. 
  * Note that many languages, such as Matlab, R and Fortran, start with 1
  
* In 2D, the first dimension corresponds to rows, the second to columns. This is known as [row-major indexing](https://numpy.org/doc/stable/glossary.html#term-row-major). 

* For multi-dimensional arrays, the order of axes in python follows C-style indexing. 
    * *The fastest varying dimension is the last dimension.* 

As a simple example, consider an array with 2 rows and 4 columns. In a row-major (or C-style) index system, values will be read in the order (from 0-7): 
```
| 0 | 1 | 2 | 3 |
| 4 | 5 | 6 | 7 | 
```
In terms of nested loops (which we should avoid if possible in our code!), this array is being accessed using: 
```
for row in rows: 
    for column in columns: 
        ...
```    
This has an impact on the time taken to access each index e.g. it is quicker to access all items in the first axes. 

For those who like to know more about this, a nice explanation can be found [here](https://agilescientific.com/blog/2018/12/28/what-is-the-fastest-axis-of-an-array).

### 1D Examples

For 1D arrays, indexing is exactly the same as discussed for lists [here](06-Built-in-Data-Structures.ipynb)

In [58]:
a = np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
a[0]

10

In [54]:
a[2:9:3] # [start:end:step]

array([30, 60, 90])

Notice that the 'end' number, 9, actually lies out of bounds (try `a[9]` and see that it gives an error).

As we saw for lists, the end-index is never included, and if you want to include all values up to the end, you could leave the *end* value blank (e.g., try `a[2::3]` and see that it gives the same result).

In [55]:
a[:3] # last is not included

array([10, 20, 30])

In [56]:
a[-2] # negative index counts from the end

80

Here we started counting 'down' from -1 (and not -0!).

### Indexing in practice

#### How to calculate x[ i ] - x[ i-1 ] without a loop?

In [59]:
x = np.random.rand(6) # create an array of random numbers (0-1)
x = np.sort(x)        # sort them in order of ascending value
print(x)

[0.26577468 0.27580301 0.27700966 0.34398536 0.68779967 0.82676837]


In [60]:
x[1:] - x[:-1]

array([0.01002832, 0.00120665, 0.0669757 , 0.34381432, 0.13896869])

In [61]:
# Note there is actually a function in NumPy that can do this for us
np.diff(x) 

array([0.01002832, 0.00120665, 0.0669757 , 0.34381432, 0.13896869])

---

## Exercise 2

Create a 2D NumPy array from the following list and assign it to the variable "a":

In [ ]:
# [[2, 3.2, 5.5, -6.4, -2.2, 2.4],
#  [1, 22, 4, 0.1, 5.3, -9],
#  [-1, 18, 6.2, 1.3, 7, -5], 
#  [3, 1, 2.1, 21, 1.1, -2]]

a) Can you guess what the following slices are equal to? Print them to check your understanding.

In [ ]:
# a[:, 3]

In [ ]:
# a[1:4, 0:4]

In [ ]:
# a[1:, 2]

b) How would you extract: i) the last column; ii) the row before last?

In [ ]:
# a[]

In [ ]:
# a[]

---

### Fancy indexing

NumPy arrays can be indexed with slices, but also with boolean or
integer arrays (e.g., masks). 


In [62]:
a = np.random.randint(1, 100, 6) # array of 6 random integers between 1 and 100
a

array([86, 68, 29, 27, 10, 34])

First, an example with an array of boolean values:

In [63]:
mask = ( a % 3 == 0 ) # Where divisible by 3 (% is the modulus operator).
mask

array([False, False, False,  True, False, False])

In [64]:
a[mask]

array([27])

Now an example with an array of integers:

In [67]:
b = np.array([0,3,5])
a[b]

array([86, 27, 34])

NB. You can pass as many integers as you like (within the axes limits), but boolean arrays will need to have the same shape as the array. 

---

## Copies and Views (a warning)

In [68]:
original = np.array([99,98,97])

other = original
other[0] = 0

What do we think has happened to the two arrays? 

In [69]:
print('other is now ',other)
print('original is now ',original)

other is now  [ 0 98 97]
original is now  [ 0 98 97]


NumPy, in its frugality, will create a *view* by default, unless told to make a copy.

You can think of this as each variable name being a pointer to the relevant object. The object itself won't be duplicated unless necessary. 

In [70]:
original = np.array([99,98,97])
copy = original.copy()
copy[0] = 0

print('copy is now ',copy)
print('original is now ',original)

copy is now  [ 0 98 97]
original is now  [99 98 97]


Be aware that views are also used when you create slices of arrays ... 

In [71]:
original = np.ones((4,3))

row = original[:,0]
row[2:] = 10 

print('row is now ',row)
print('original is now \n',original)

row is now  [ 1.  1. 10. 10.]
original is now 
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [10.  1.  1.]
 [10.  1.  1.]]


... but not when you use "fancy" indexing.  

In [75]:
original = np.ones((4,3))

fancy = original[[0,1,2,3],0]
fancy[2:] = 10 

print('fancy is now ',fancy)
print('original is now \n',original)

fancy is now  [ 1.  1. 10. 10.]
original is now 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**To avoid this leading to errors propagating through your data, be sure to check whether a copy is needed.** 

### Copies in functions vs. methods


From help(numpy):

```
Most of the functions in `numpy` return a copy of the array argument
(e.g., `np.sort`).  In-place versions of these functions are often
available as array methods, i.e. ``x = np.array([1,2,3]); x.sort()``.
Exceptions to this rule are documented.
```

In [80]:
original = np.array([99,98,97])

# Function np.sort
sortedCopy = np.sort(original)
print(f'sort function: original = {original}, returned = {sortedCopy}')

# Method sort()
original.sort()
print(f'sort method: original = {original}')


sort function: original = [99 98 97], returned = [97 98 99]
sort method: original = [97 98 99]


No new variable (or copy) is created with the method - methods act on the array they're attached to.  
So using `.sort()` is equivalent to: 
```
orginal = np.sort(original)
```

---

## NumPy Statistics 

NumPy has a large number of useful methods and functions, enabling you to perform statistical operations on arrays. 

A full list can be found in the [NumPy documentation](https://numpy.org/doc/stable/reference/index.html), but a selection of useful methods and functions are provided below. 

### Statistical methods of arrays

In [81]:
a1d=np.random.normal(0,10,5) 
print('array a1d                       :', a1d)
print('Minimum and maximum             :', a1d.min(), a1d.max())
print('Index of minimum and maximum    :', a1d.argmin(), a1d.argmax())
print('Sum and product of all elements :', a1d.sum(), a1d.prod())
print('Mean and standard deviation     :', a1d.mean(), a1d.std())


array a1d                       : [-4.71232979  8.79186404 -0.3918196  -7.55948715  0.85970841]
Minimum and maximum             : -7.559487153192945 8.791864038218778
Index of minimum and maximum    : 3 1
Sum and product of all elements : -3.0120640911957923 -105.49850454791573
Mean and standard deviation     : -0.6024128182391585 5.5808043587878435


A full list of available methods can be found [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

### Statistical functions

https://numpy.org/doc/stable/reference/routines.statistics.html    

In [84]:
print('Median and percentile           :', np.median(a1d), np.percentile(a1d,75))

Median and percentile           : -0.39181959802858224 0.8597084106363845


### Operations over a given axis

In [85]:
print(a2d)
print('sum  :',a2d.sum())
print('sum  :',a2d.sum(axis=0))
print('sum  :',a2d.sum(axis=1))

[[10. 20. 30.]
 [ 9.  8.  5.]]
sum  : 82.0
sum  : [19. 28. 35.]
sum  : [60. 22.]


### What about NaN values?

A series of functions are available that will excluding NaN values (missing numbers) from your calculations.

In [86]:
a1d[2] = np.nan
print(a1d)

[-4.71232979  8.79186404         nan -7.55948715  0.85970841]


In [89]:
print('mean  :',np.mean(a1d))
print('nanmean  :',np.nanmean(a1d))

mean  : nan
nanmean  : -0.6550611232918025


### Vectorisation: operations on whole arrays

In [113]:
a = np.random.rand(4)
b = np.random.rand(4)
print(a, b)

result = np.exp(a/100.)/b

print(result)

[0.64542472 0.04885673 0.96927537 0.39714696] [0.05149628 0.53421404 0.74007236 0.69063119]
[19.54461727  1.87282366  1.36437995  1.45371275]


In [114]:
# Non-vectorised
result=np.zeros(a.shape)   # create an array to hold the results

for i in range(a.size): 
    result[i] = np.exp(a[i]/100.)/b[i]
    
print(result)

[19.54461727  1.87282366  1.36437995  1.45371275]


Vectorization is generally faster than using `for` loops. 

However, for more complicated algorithms it might not always be possible, or the most readable


---

## Exercise 3

Consider a 4 x 5 2D array of negative integers:

In [120]:
a = np.arange(0, 100, 5).reshape(4, 5) 
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

Suppose you want to return an array `result`, which has the squared value when an element in array `a` is greater than `15` and less than `65`, and is 1 otherwise.

Using a `for` loop, the result would look like this:

In [125]:
result = np.zeros(a.shape, dtype=a.dtype)    # pre-allocate the result array

for i in range(a.shape[0]):                  # loop over rows
    for j in range(a.shape[1]):              # loop over columns
        if a[i, j] > 15 and a[i, j] < 65:    # only square the number if within the chosen limits
            result[i, j] = a[i, j]**2
        else:                                # set to 1 otherwise
            result[i, j] = 1
            
result

array([[   1,    1,    1,    1,  400],
       [ 625,  900, 1225, 1600, 2025],
       [2500, 3025, 3600,    1,    1],
       [   1,    1,    1,    1,    1]])

**Can you write a vectorised solution?**

Hint: use np.logical_and() to create a condition for indexing (information on all NumPy's logic functions can be found [here](https://numpy.org/doc/stable/reference/routines.logic.html)). 


In [ ]:
# Your code here



---
---

## Masked arrays - how to handle (propagating) missing values

![](../figures/masked_array.png)

All operations related to masked arrays live in `numpy.ma` submodule.

The simplest example of manual creation of a masked array:

In [126]:
a = np.ma.masked_array(data=[1, 2, 3],
                       mask=[True, True, False],
                       fill_value=-999)
a

masked_array(data=[--, --, 3],
             mask=[ True,  True, False],
       fill_value=-999)

Often, a task is to mask array depending on a criterion.

In [127]:
a = np.linspace(1, 15, 15)

In [128]:
masked_a = np.ma.masked_greater_equal(a, 11)

In [129]:
masked_a

masked_array(data=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, --,
                   --, --, --, --],
             mask=[False, False, False, False, False, False, False, False,
                   False, False,  True,  True,  True,  True,  True],
       fill_value=1e+20)

Note: In a masked array, unlike setting values to NaN, the raw data still exists, should you need it. 

In [130]:
masked_a.data

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

---

## Exercise 4

1. Create a "data" array of evenly spaced numbers, in the interval (-10, 20) spaced by 0.5
2. Calculate the (natural) logarithm of the data
3. Create a condition i.e. a True/False (boolean) array, that you can use to mask these results
    - The resulting array should be masked when either of the following conditions apply
        - larger than -1 and smaller than 1 
        - data is not a real number
4. Mask the array depending on these conditions


In [ ]:
# Your code:
# 1. Hint: use `np.linspace` or `np.arange` functions


In [ ]:
# 2.

In [ ]:
# 3. Hint: use np.isfinite


In [ ]:
# 4. Hint: use np.ma.masked_where(condition,arr)


---
---

## Shape manipulation

In [131]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [132]:
print( f'array: \n {a}' )
print( f'shape: {a.shape}' )

array: 
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)


In [133]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [134]:
a.repeat(4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6])

In [135]:
a.reshape((3, 2)) # NB. new shape must be consistent with number of values. 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [136]:
print( f'Old shape: {a.shape}' )
print( f'New shape: {a.reshape((3, 2)).shape}' )

Old shape: (2, 3)
New shape: (3, 2)


---
## Exercise 5

Generate a 2d array with shape 5x5. The first value is 0 and it grows left to right and top to bottom in increments of 0.1.

In [ ]:
# Your code here


---
## Further axes manipulation


We saw earlier that it is possible to *transpose* an array i.e. flip the order of axes. 

The `transpose` function can also be used more generally to change the order of axes within an array. 


In [ ]:
a3d = np.ones((4,3,2))
print(a3d.shape)

new_order = np.transpose(a3d,[1, 2, 0]) # numbers in list refer to axes
print(new_order.shape)

#### Dimensions can also be added

In [ ]:
a3d[..., np.newaxis].shape

---

## Broadcasting

The fact that NumPy operates on an element-wise basis means that in principle arrays must always match one another's shape. However, NumPy will also helpfully "broadcast" dimensions when possible. 

**The Broadcasting Rule**  
In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

In [141]:
# Example

a1d = np.arange(0,5)
a2d = np.zeros((5,3))
print(a1d)
print(a2d)

# try:
# a1d + a2d

# add a trailing axis: 
# a1d[..., np.newaxis] + a2d

# this would also work: 
# a1d.reshape(5,1) + a2d

[0 1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## References
* [NumPy docs](https://numpy.org/doc/stable/)
* [SciPy lectures](http://www.scipy-lectures.org/)

**If you're moving from Matlab to python, this link could be particularly useful:** 
* **[NumPy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)**
   * Contains a reference table of Matlab-NumPy equivalents.