# Solutions for the exercises in the notebook: Introduction to numpy

In [1]:
import numpy as np

# Exercise 1

In [5]:
# a) Create an array with units of seconds through the day, from 00:00 to 24:00, inclusive 
# b) Create new arrays that still have units of seconds but have 1 minute or 1 hour intervals.
# (enter your code below)

In [8]:
# a)
np.arange(0,86401)
# or: 
# np.linspace(0,86400,86401)

array([    0,     1,     2, ..., 86398, 86399, 86400])

In [12]:
# b)
np.arange(0,86401,60) # minutes
np.arange(0,86401,60*60) # hours
# or: 
# np.linspace(0,86400,24*60+1) # minutes
# np.linspace(0,86400,24+1) # hours

array([    0,  3600,  7200, 10800, 14400, 18000, 21600, 25200, 28800,
       32400, 36000, 39600, 43200, 46800, 50400, 54000, 57600, 61200,
       64800, 68400, 72000, 75600, 79200, 82800, 86400])

---

# Exercise 2

Create a 2D NumPy array from the following list and assign it to the variable "a":

In [ ]:
# [[2, 3.2, 5.5, -6.4, -2.2, 2.4],
#  [1, 22, 4, 0.1, 5.3, -9],
#  [-1, 18, 6.2, 1.3, 7, -5], 
#  [3, 1, 2.1, 21, 1.1, -2]]

In [13]:
# Solution
a=np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
  [1, 22, 4, 0.1, 5.3, -9],
  [-1, 18, 6.2, 1.3, 7, -5], 
  [3, 1, 2.1, 21, 1.1, -2]])

print(a)

[[ 2.   3.2  5.5 -6.4 -2.2  2.4]
 [ 1.  22.   4.   0.1  5.3 -9. ]
 [-1.  18.   6.2  1.3  7.  -5. ]
 [ 3.   1.   2.1 21.   1.1 -2. ]]


a) Can you guess what the following slices are equal to? Print them to check your understanding.

In [14]:
a[:, 3]
# This is the 4th column of a (recall that we start indexing with 0)

array([-6.4,  0.1,  1.3, 21. ])

In [15]:
a[1:4, 0:4]
# rows 1 to 4 (second to last) and columns first to fourth

array([[ 1. , 22. ,  4. ,  0.1],
       [-1. , 18. ,  6.2,  1.3],
       [ 3. ,  1. ,  2.1, 21. ]])

In [17]:
a[1:, 2]
# All rows starting from the second, from the third column

array([4. , 6.2, 2.1])

b) How would you extract: i) the last column; ii) the row before last?

In [18]:
# i)
a[:,-1] # This is the last column

array([ 2.4, -9. , -5. , -2. ])

In [19]:
# ii)
a[-2,:] # This is the row before last

array([-1. , 18. ,  6.2,  1.3,  7. , -5. ])

---

# Exercise 3

Consider a 4 x 5 2D array of negative integers:

In [23]:
a = np.arange(0, 100, 5).reshape(4, 5) 
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

Suppose you want to return an array `result`, which has the squared value when an element in array `a` is greater than `15` and less than `65`, and is 1 otherwise.

Using a `for` loop, the result could look like this:

In [24]:
result = np.zeros(a.shape, dtype=a.dtype)    # pre-allocate the result array

for i in range(a.shape[0]):                  # loop over rows
    for j in range(a.shape[1]):              # loop over columns
        if a[i, j] > 15 and a[i, j] < 65:    # only square the number if within the chosen limits
            result[i, j] = a[i, j]**2
        else:                                # set to 1 otherwise
            result[i, j] = 1
            
result

array([[   1,    1,    1,    1,  400],
       [ 625,  900, 1225, 1600, 2025],
       [2500, 3025, 3600,    1,    1],
       [   1,    1,    1,    1,    1]])

**Can you write a vectorised solution?**

Hint: use np.logical_and() to create a condition for indexing (information on all NumPy's logic functions can be found [here](https://numpy.org/doc/stable/reference/routines.logic.html)). 

In [26]:
# Example solution 1: 

result = np.ones(a.shape,dtype=a.dtype)          # set all values to 1 at start
condition = np.logical_and( a>15, a<65 )         # create a boolean array -> true within set limits
result[condition] = np.square(a[condition])      # only square values where condition==true.
print(result)

[[   1    1    1    1  400]
 [ 625  900 1225 1600 2025]
 [2500 3025 3600    1    1]
 [   1    1    1    1    1]]


In [27]:
# Example solution 2 - A one-liner using `np.where`:

result = np.where(np.logical_and( a>15, a<65 ), a**2, 1)
print(result)

[[   1    1    1    1  400]
 [ 625  900 1225 1600 2025]
 [2500 3025 3600    1    1]
 [   1    1    1    1    1]]


In [31]:
# help(np.where)


---

# Exercise 4

1. Create a "data" array of evenly spaced numbers, in the interval (-10, 20) spaced by 0.5
2. Calculate the (natural) logarithm of the data
3. Create a condition i.e. a True/False (boolean) array, that you can use to mask these results
    - The resulting array should be masked when either of the following conditions apply
        - larger than -1 and smaller than 1 
        - data is not a real number
4. Mask the array depending on these conditions


In [32]:
# Your code:
# Hint: use `np.linspace` or `np.arange` functions

# 1. 
data = np.arange(-10,20.1,0.5)
print(data)

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10.   10.5  11.   11.5  12.   12.5  13.   13.5
  14.   14.5  15.   15.5  16.   16.5  17.   17.5  18.   18.5  19.   19.5
  20. ]


In [33]:
# 2.
logdata = np.log(data)
print(logdata)

[        nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan        -inf -0.69314718  0.          0.40546511
  0.69314718  0.91629073  1.09861229  1.25276297  1.38629436  1.5040774
  1.60943791  1.70474809  1.79175947  1.87180218  1.94591015  2.01490302
  2.07944154  2.14006616  2.19722458  2.2512918   2.30258509  2.35137526
  2.39789527  2.44234704  2.48490665  2.52572864  2.56494936  2.60268969
  2.63905733  2.67414865  2.7080502   2.74084002  2.77258872  2.80336038
  2.83321334  2.86220088  2.89037176  2.91777073  2.94443898  2.97041447
  2.99573227]


C:\Users\JG10\AppData\Local\Temp\ipykernel_836\1934390118.py:2: RuntimeWarning: divide by zero encountered in log
  logdata = np.log(data)
C:\Users\JG10\AppData\Local\Temp\ipykernel_836\1934390118.py:2: RuntimeWarning: invalid value encountered in log
  logdata = np.log(data)


In [37]:
# 3. Hint: use np.isfinite
condition = np.logical_or(~np.isfinite(logdata), np.logical_and(logdata>-1,logdata<1))
print(condition)

#Another possible condition giving the same result would be:
condition = np.logical_or(np.logical_not(np.isfinite(logdata)), np.abs(logdata)<1)
print(condition)


[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False]


In [38]:
# 4. Hint: use np.ma.masked_where(condition,arr)

masked_arr= np.ma.masked_where(condition, logdata)
print(masked_arr)

[-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
 -- -- 1.0986122886681098 1.252762968495368 1.3862943611198906
 1.5040773967762742 1.6094379124341003 1.7047480922384253
 1.791759469228055 1.8718021769015913 1.9459101490553132
 2.0149030205422647 2.0794415416798357 2.1400661634962708
 2.1972245773362196 2.2512917986064953 2.302585092994046
 2.3513752571634776 2.3978952727983707 2.4423470353692043
 2.4849066497880004 2.5257286443082556 2.5649493574615367
 2.6026896854443837 2.6390573296152584 2.6741486494265287 2.70805020110221
 2.740840023925201 2.772588722239781 2.803360380906535 2.833213344056216
 2.8622008809294686 2.8903717578961645 2.917770732084279
 2.9444389791664403 2.970414465569701 2.995732273553991]


---

# Exercise 5

Generate a 2d array with shape 5x5. The first value is 0 and it grows left to right and top to bottom in increments on 0.1.

In [40]:
a2d = np.arange(0.,2.5,.1)
a2d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4])

In [41]:
#Another possibility
a2d=np.linspace(0.,2.4,25)
a2d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4])

In [42]:
a2d.reshape([5,5])

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4]])